apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:2.1.8
        volumeMounts:
          - name: config
            mountPath: /fluent-bit/etc/
          - name: varlog
            mountPath: /var/log
      volumes:
        - name: config
          configMap:
            name: fluentbit-config
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
        - name: varlog
          hostPath:
            path: /var/log
---
apiVersion: v1
kind: Service
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  selector:
    app: fluentbit
  ports:
    - port: 2020
      targetPort: 2020
